### ISSUE TITLE
Version Check Issue

### ISSUE THREAD

**Issue by ghost** [VORPCORE/vorp_barbershop_lua#1]
I recently updated vorp_barbershop to get the new version check. It seems like it is breaking the server console print somewhere. I commented out 'ensure vorp_barbershop' and the print appeared again. 

![Version Check](https://user-images.githubusercontent.com/57041193/168431428-9cc986d4-10ba-4d33-ba4e-f68028a5a8f7.PNG)

**Comment by outsider31000** [comment]
Can you show the issue?

**Comment by outsider31000** [comment]
Change in the fxmanifest on the last line the path to the repo it should be vorp_barbershop-lua and not vorp-barbershop-lua

**Comment by ghost** [comment]
I changed it and the issue still persists. It looks like it is the same for vorp_hunting as well. I downloaded the latest versions to both this morning. When I comment both resources out the print will happen in the server console but when I have them both started it won't print in the console. Below is what both manifests look like:

![image](https://user-images.githubusercontent.com/57041193/168437641-7303a6cf-3795-4f74-ac3b-120b5868b75e.png)
![image](https://user-images.githubusercontent.com/57041193/168437694-0df97d0c-b926-4493-9220-0694ae10ae79.png)

With them commented out:

![image](https://user-images.githubusercontent.com/57041193/168438190-845217f1-63b8-49ba-9f52-4070faf2e94f.png)

With them started:

![image](https://user-images.githubusercontent.com/57041193/168438827-e1451172-3ed9-4089-998c-125366da2044.png)

**Comment by ghost** [comment]
Barbershop is working now. This is what I changed the manifest to:

![image](https://user-images.githubusercontent.com/57041193/168439133-9ee85254-18ae-4cfd-b722-7acd69a82a02.png)

![image](https://user-images.githubusercontent.com/57041193/168439456-c5857279-08cd-4695-9840-36b556f1b753.png)

I can't figure out why vorp_hunting would be stopping the console print.

**Comment by outsider31000** [comment]
The server already does the request https no need to add it. It just takes sometime to updated. It should be only the way i wrote.

**Comment by outsider31000** [comment]
I seethe issue with vorp hunting.  You have to add vorp_hunting/vorp_hunting cause its in a subfolder xD

**Comment by ghost** [comment]
I updated the manifest to what I have below, but it still won't print. 

![image](https://user-images.githubusercontent.com/57041193/168440109-b15c4e80-23e2-4cfc-a4b5-9a87f2bcacf0.png)

I even tried changing to this link and it didn't work: https://github.com/VORPCORE/VORP-Hunting/tree/main/vorp_hunting

**Comment by outsider31000** [comment]
you can't do anything in your versions. if in the repo is wrong then it would never work. so i dont know  why are you changing things.

**Comment by outsider31000** [comment]
it needs to update in the repo not in what you have. because the repo was wrong. try now and see if its fixed download again

**Comment by ghost** [comment]
I downloaded again and it still persists:

vorp_hunting commented out:

![image](https://user-images.githubusercontent.com/57041193/168440546-b588dee7-e55b-4a0d-85fb-76d94477cb62.png)

vorp_hunting started:

![image](https://user-images.githubusercontent.com/57041193/168440577-6059aa01-1cdd-45c1-aaa0-dca85bd22179.png)

**Comment by outsider31000** [comment]
try now download and restart it works now the version file was in the wrong place

**Comment by ghost** [comment]
Still seeing the same result after a new download. Print won't work when started.

**Comment by ghost** [comment]
Changed manifest back to this and now its working since the version file was moved:

![image](https://user-images.githubusercontent.com/57041193/168441557-abea83eb-0d4a-4d0e-99b5-e122b9374c18.png)

**Comment by outsider31000** [comment]
great
